---
title: "CDC Corona Virus as of Mar. 30,2020"
author: "David J Jackson"
date: "3/22/2020"
output: html_document
---

```{r setup, include=FALSE,echo=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(DT)
library(pracma)
library(plotly)
library(scales)
library(prophet)
library(readxl)
library(httr)
library(lubridate)
```
```{r, echo=FALSE}
rm(list=ls())
# these libraries are necessary
#create the URL where the dataset is stored with automatic updates every day

url <- paste("https://www.ecdc.europa.eu/sites/default/files/documents/COVID-19-geographic-disbtribution-worldwide-",format(Sys.time(), "%Y-%m-%d"), ".xlsx", sep = "")

#download the dataset from the website to a local temporary file
GET(url, authenticate(":", ":", type="ntlm"), write_disk(tf <- tempfile(fileext = ".xlsx")))
#read the Dataset sheet into “R”
CDC <- read_excel(tf)
```



```{r,echo=FALSE}

CDC$DateRep <- lubridate::ymd(CDC$DateRep)
# CDC$DateRep <- as.Date(CDC$DateRep)
CDC$DCount <- ifelse(CDC$Deaths ==0,"NO","YES")
colnames(CDC) <- c("Reported","Day","Month","Year","Cases","Deaths","Countries","GeoId","DCount")
CDC$Countries <-ifelse(CDC$Countries=="United_States_of_America","USA",CDC$Countries)
CDC$Countries <-ifelse(CDC$Countries=="Cases_on_an_international_conveyance_Japan","Japan",CDC$Countries)
```
```{r}
# Calculate Weekly Summary Cases and Deaths(World)
# World
CDC_weekly <- CDC %>% group_by(Weekly =floor_date( Reported,"week")) %>% summarise(
                                                        tc = sum(Cases),
                                                        td = sum(Deaths),                                                                 perdeaths = td/tc,
                                                        Count = n())
# By Country
Countries_weekly <- CDC %>% group_by(Countries,Weekly =floor_date( Reported,"week")) %>% summarise(
                                                        tc = sum(Cases),
                                                        td = sum(Deaths),                                                                 perdeaths = td/tc,
                                                        Count = n())

# USA Only
US_weekly <- Countries_weekly %>% filter(Countries == "USA" )

```

### The World: Summary by Week for Cases,Deaths and Percent of Deaths

```{r, echo=FALSE}
CDC_weekly %>% plot_ly() %>% add_lines(x=~Weekly,y=~tc) %>% 
        layout(title="The World: Total Cases By Week")


CDC_weekly %>% plot_ly() %>% add_lines(x=~Weekly,y=~td) %>% 
        layout(title="The World: Total Deaths By Week")

CDC_weekly %>% plot_ly() %>% add_lines(x=~Weekly,y=~perdeaths) %>% 
        layout(title="The World: Percent of Cases Ending in Death by Week") 
      
```

### US Summary by Week of Cases,Deaths and Percent of Deaths

```{r}

US_weekly %>% plot_ly() %>% add_lines(x=~Weekly,y=~tc) %>% 
        layout(title="USA: Total Cases By Week")
US_weekly %>% plot_ly() %>% add_lines(x=~Weekly,y=~td) %>% 
        layout(title="USA: Total Deaths By Week")
US_weekly %>% plot_ly() %>% add_lines(x=~Weekly,y=~perdeaths) %>% 
        layout(title="USA Percent of Cases Ending in Death by Week")
```


### Reported Cases by Date

```{r,echo=FALSE}
# CDC %>% group_by(Countries) %>% summarise(Count = n()) %>% datatable()
```
```{r, echo=FALSE}
CDC %>% ggplot() +geom_col(aes(x=Reported,y=Cases)) +
    theme(axis.text.x = element_text(angle = 90, hjust = 1)) + 
  scale_y_continuous() + labs(title="The Whole Shooting Match") +
  facet_wrap(~Year)

```
```{r, echo=FALSE}
coron_country <- CDC %>% filter(Countries !="China")
  ggplot(coron_country) +geom_col(aes(x=Reported,y=Cases)) +
    facet_wrap(~Year) + 
    theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
    scale_y_continuous() + labs(title="World Wide Reported Cases  minus China")

```

### Just China

```{r, echo=FALSE}
coron_china <- CDC %>% filter(Countries =="China")
  ggplot(coron_china) +geom_col(aes(x=Reported,y=Cases)) +
    facet_wrap(~Year) + 
    theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
    scale_y_continuous() + labs(title="Just China")
```


```{r, echo=FALSE}
coron_usa <- CDC %>% filter(GeoId =="US")
ggplot(coron_usa) +geom_col(aes(x=Reported,y=Cases)) +
    theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
    scale_y_continuous() + facet_wrap(~Year) +
  labs(title="US Reported Cases by Month as of Mar. 20, 2020",x="Date Reported")
```

### Reported Deaths by Date

```{r, echo=FALSE}
CDC %>% ggplot() +geom_col(aes(x=Reported,y=Deaths)) +
    theme(axis.text.x = element_text(angle = 90, hjust = 1)) + 
  scale_y_continuous() + labs(title="Deaths: The Whole Shooting Match") +
  facet_wrap(~Year)

```
```{r, echo=FALSE}
coron_country <- CDC %>% filter(Countries !="China")
  ggplot(coron_country) +geom_col(aes(x=Reported,y=Deaths)) +
    facet_wrap(~Year) + 
    theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
    scale_y_continuous() + labs(title=" Deaths: The World minus China")
  
 coron_china <- CDC %>% filter(Countries =="China")
  ggplot(coron_country) +geom_col(aes(x=Reported,y=Deaths)) +
    facet_wrap(~Year) + 
    theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
    scale_y_continuous() + labs(title=" Deaths: Just China")
  
coron_usa %>% ggplot() +   geom_col(aes(x=Reported,y=Deaths)) +
          facet_wrap(~Year) +
          labs(title="US Deaths by Month as of Mar. 20,2020",x="Date Reported")



```

## Death Rate as a Percentage(%) of Cases(>=200)

```{r,echo=FALSE}
death_percent <- CDC %>% group_by(Countries) %>% summarise(
                                TCases = sum(Cases),
                                TDeaths = sum(Deaths),
                                PDeaths =TDeaths/TCases *100,
                                ) %>% filter(TCases >200)
death_percent$PDeaths <- round(death_percent$PDeaths,digits = 2)
                        
```
```{r,echo=FALSE}

death_percent %>%
  mutate(Countries = fct_reorder(Countries, PDeaths)) %>%
  ggplot() + geom_col(aes(x=PDeaths,y=Countries)) +
  labs(title="Death Rate Percentage by Country(AS OF Mar. 20,2020",subtitle="With 200  or more reported cases",x="Death Rate Percentage")
```
```{r,echo=FALSE}
# death_percent %>% datatable()
```

## Death Rate Percentage of Cases(>1000)

```{r,echo=FALSE}
death_1000 <- CDC %>% group_by(Countries) %>% summarise(
                                TCases = sum(Cases),
                                TDeaths = sum(Deaths),
                                PDeaths =TDeaths/TCases *100,
                                ) %>% filter(TCases >=1000)
death_1000$PDeaths <- round(death_1000$PDeaths,digits = 1)
```

```{r,echo=FALSE}
death_1000 %>%
  mutate(Countries = fct_reorder(Countries, TCases)) %>%
  ggplot() + geom_col(aes(x=TCases,y=Countries)) +
  labs(title="Total Reported Case by Country as of Mar. 20 ,2020",subtitle="With 1000  or more reported cases",x="Number of Cases")
```

##  Cases by Country as Ratio of the Whole World

```{r}
daily_cases <- CDC %>% group_by(Reported) %>% summarise(
                                          total_cases = sum(Cases,
                                          case_count = n())) 

daily_cases_country <- CDC %>% group_by(Countries,Reported) %>% summarise(
                                          Country_cases = sum(Cases),
                                          Country_Count = n()) 

daily_cases_combined <- left_join(daily_cases,daily_cases_country,by="Reported")
daily_cases_combined$Per_Case <- daily_cases_combined$Country_cases/daily_cases_combined$total_cases
daily_cases_combined_usa <- daily_cases_combined %>% filter(Countries=="USA")

USA_cases <- daily_cases_combined_usa 
gg1 <- ggplot(USA_cases) + geom_line(aes(x=Reported,y=Per_Case)) +
  scale_y_continuous(labels=scales::percent) +
  labs(title="USA Reported Case as a Ratio of Total World, As of Mar. 20,2020")
ggplotly(gg1)
```

## Deaths by Country as a Ratio of the Whole World

```{r}
## Daily Deaths

daily_deaths <- CDC %>% group_by(Reported) %>% summarise(
                                          Deaths_Total = sum(Deaths,
                                          CountD = n())) 
                                          
daily_deaths_counties <- CDC %>% group_by(Countries,Reported) %>% summarise(
                                          Country_Deaths = sum(Deaths,
                                          CountD = n())) 
                                          

daily_deaths_combined <- left_join(daily_deaths,daily_deaths_counties,by="Reported")
```
```{r}
daily_deaths_combined$PercentDeaths <- daily_deaths_combined$Country_Deaths/daily_deaths_combined$Deaths_Total
daily_deaths_combined_usa <- daily_deaths_combined %>% filter(Countries=="USA")

USA_deaths <- daily_deaths_combined_usa 

gg <- ggplot(USA_deaths) + geom_line(aes(x=Reported,y=PercentDeaths)) +
  scale_y_continuous(labels=scales::percent) +
  labs(title="USA Reported Deaths as a Ratio of Total World as of Mar. 20, 2020")
ggplotly(gg)
```
```{r}
CDC$X <- ifelse(CDC$Cases==0,0,1)
CDC %>% ggplot() +geom_point(aes(x=Cases,y=Deaths)) +
        geom_smooth(aes(x=Cases,y=Deaths),method=glm)
  
```
