---
title: "ECDC COVID-19 Excel Spreadsheet"
author: "David J Jackson"
date: "4/5/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(fig.width=9, fig.height=6)
library(tidyverse)
library(forecast)
library(data.table)
library(lubridate)
library(RSQLite)
theme_set(theme_linedraw())
```
```{r,echo=FALSE}
rm(list=ls())
db <- dbConnect(SQLite(), dbname="../db/CORVID.sqlite3")
ECDC <- dbGetQuery(db,"select Reported,Cases,Deaths,Countries,
                 CountryCode  from ECDC")
colnames(ECDC) <- c("Date","Cases","Deaths","Countries","Code" )
ECDC$Date <- as.Date(ECDC$Date)



```
```{r,echo=FALSE}
USA <- ECDC %>% filter(Code=="USA")
USA_date <- ECDC %>% filter(Code=="USA" & Date >=Sys.Date() -30)
```

### USA Total Cases and Deaths by Day and Week

```{r,echo=FALSE}
USA_date %>% ggplot() + geom_col(aes(x=factor(Date),y=Cases)) +
  labs(title="USA Daily Case Totals (Previous 30 Days)") +
  theme(axis.text.x=element_text(angle =90))
```
```{r,echo=FALSE}
USA_date %>% ggplot() + geom_col(aes(x=Date,y=Deaths)) +
  labs(title="USA Daily Deaths Totals (Previous 30 Day)") +
  theme(axis.text.x = element_text(angle = 90))

```
```{r,echo=FALSE}
USA_weekly <- USA %>% group_by(Weekly =floor_date(Date,"week")) %>% 
  summarise(
             tc = sum(Cases),
             td = sum(Deaths),                                                                    perdeaths = td/tc, Count = n())
```
```{r,echo=FALSE}
USA_weekly %>% ggplot() + geom_col(aes(x=factor(Weekly),y=tc)) +
  labs(title="USA Weekly Case Totals") +
  theme(axis.text.x = element_text(angle = 90))

```
```{r,echo=FALSE}
USA_weekly  %>% ggplot() + geom_col(aes(x=factor(Weekly),y=td)) +
  labs(title="USA Weekly Deaths Totals") +
  theme(axis.text.x = element_text(angle = 90))

```

### Pakistan Total Cases and Deaths by Day and Week

```{r,echo=FALSE}
PAK <- ECDC %>% filter(Code=="PAK")
PAK30 <- ECDC %>% filter(Code=="PAK" & Date >=Sys.Date() -30)
```
```{r,echo=FALSE}
PAK30 %>% ggplot() + geom_col(aes(x=Date,y=Cases)) +
  labs(title="Pakistan Daily Case Totals",subtitle="(Previous 30 Days)") +
  theme(axis.text.x = element_text(angle = 90))

```
```{r,echo=FALSE}
PAK30 %>% ggplot() + geom_col(aes(x=Date,y=Deaths)) +
  labs(title="Pakistan Daily Deaths Totals",subtitle="(Previous 30 Days)") +
  theme(axis.text.x = element_text(angle = 90))

```
```{r,echo=FALSE}
PAK_weekly <- PAK %>% group_by(Weekly =floor_date( Date,"week")) %>% 
  summarise(
             tc = sum(Cases),
             td = sum(Deaths),                                                                    perdeaths = td/tc, Count = n())
```
```{r,echo=FALSE}
PAK_weekly %>% ggplot() + geom_col(aes(x=factor(Weekly),y=tc)) +
  labs(title="Pakistan Weekly Case Totals") +
  theme(axis.text.x = element_text(angle = 90))

```
```{r,echo=FALSE}
PAK_weekly  %>% ggplot() + geom_col(aes(x=factor(Weekly),y=td)) +
  labs(title="Pakistan Weekly Deaths Totals") +
  theme(axis.text.x = element_text(angle = 90))

```
```{r}
dbDisconnect(db)
```